spring.application.name=Assigment3
spring.datasource.url=jdbc:postgresql://ep-autumn-recipe-am8tkmh0-pooler.c-5.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_GaVJx5gX6tPN&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ItBDoHYZ6l4N
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE